### PR TITLE
redirect access.log to stdout

### PR DESCRIPTION
**Pull request by cru-Luis-Rodriguez**

### CODE REVIEW

**Comment by mattdrees** [comment]
closed intentionally? this seems like the right thing to do

**Comment by Omicron7** [comment]
I agree, this is the solution. I was waiting it hear from @mattdrees about not logging `/socket.io` requests so we could possibly add an nginx location to disable access logs for those.

**Comment by cru-Luis-Rodriguez** [comment]
@mattdrees @Omicron7 
yes, I closed it as I thought there was going to be a different solution applied. 
I can go ahead and re-open.

**Comment by mattdrees** [comment]
ah, sorry. I didn't have a strong opinion about socket.io logs. Certainly fine to disable it.

**Review by mattdrees — APPROVED** [review]
Agree it might be good to reduce logs, but I'm also OK with shipping this PR as-is before that happens.

**Pull request merged**
